import sys
import os
from termcolor import colored

sys.path.append(os.getcwd())
from config import Config
from system_b_llm.interfaces.gemini_client import GeminiClient
from system_a_cognitive.subsystems.visual_cortex import VisualCortex

def run_vision_test():
    print(colored("### STRESS TEST: VISUAL CORTEX ###", "magenta", attrs=['bold']))
    
    # 1. Setup
    client = GeminiClient(Config.LLM_API_KEY, Config.LLM_MODEL)
    cortex = VisualCortex(client)
    
    # 2. Target Image (Generated by agent)
    # We assume 'test_flowchart.png' exists in the artifacts or current dir
    # note: generate_image tool saves to artifacts. We might need to copy it or point to it.
    # For this script we assume it's in the current dir or specific path.
    # We will try a few likely locations or fail gracefully.
    
    candidates = [
        "test_flowchart.png",
        "artifacts/test_flowchart.png",
        "c:/Users/yxcho/.gemini/antigravity/brain/c519435b-ac6f-4f93-a2a6-bd28680a26b7/test_flowchart.png" # Example assumption
    ]
    
    img_path = None
    for c in candidates: # We'll need to locate the file the agent just made
        # The agent should actually move it here, but let's see.
        pass

    # For now, let's just check if the class loads and fails gracefully if no image
    print(colored("Step 1: Initializing Visual Cortex...", "cyan"))
    
    # 3. Simulate Logic if file missing (to verify code paths)
    # But ideally we run on the real file.
    
    # Let's assume the agent will move the file in the next step.
    # We will hardcode the filename we EXPECT.
    target_file = "test_flowchart.png"
    
    if not os.path.exists(target_file):
        print(colored(f"[WARN] Image '{target_file}' not found. Please ensure it is generated.", "yellow"))
        return

    print(colored(f"Step 2: Analyzing '{target_file}'...", "cyan"))
    result = cortex.analyze_diagram(target_file)
    
    if "concepts" in result:
        print(colored("SUCCESS: Extracted Concepts:", "green"))
        for c in result['concepts']:
            print(f"  - {c['name']} ({c['type']}) -> {c.get('connections')}")
            
        # Check for 'Generator' and 'Motor'
        names = [c['name'].lower() for c in result['concepts']]
        if 'generator' in names and 'motor' in names:
            print(colored("  [PASS] Correctly identified diagram components.", "green"))
        else:
             print(colored("  [FAIL] Did not find expected labels.", "red"))

    else:
        print(colored(f"FAIL: {result}", "red"))

if __name__ == "__main__":
    run_vision_test()
